#!/usr/bin/env python3
"""Write assets/manifest.js listing every image and sound so the game can preload them."""
import os, json
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')); IMG = os.path.join(ROOT, 'assets', 'img'); AUD = os.path.join(ROOT, 'assets', 'audio')
imgs = []
for d in sorted(os.listdir(IMG)):
    p = os.path.join(IMG, d)
    if os.path.isdir(p):
        files = sorted(os.listdir(p))
        for f in files:
            if f.endswith('.png') and f[:-4] + '.jpg' in files: continue  # jpg version wins
            if f.endswith(('.png', '.jpg')): imgs.append(f"{d}/{f}")
snds = sorted(f[:-4] for f in os.listdir(AUD) if f.endswith('.ogg'))
with open(os.path.join(ROOT, 'assets', 'manifest.js'), 'w') as fh:
    fh.write('// generated by tools/list_assets.py\n')
    fh.write('const ASSET_IMAGES = ' + json.dumps(imgs) + ';\n'); fh.write('const ASSET_SOUNDS = ' + json.dumps(snds) + ';\n')
print(len(imgs), 'images', len(snds), 'sounds')
