// ===== UNDRAWN boot =====
'use strict';
(async function boot() {
  const canvas = document.getElementById('game'); const ctx = canvas.getContext('2d');
  let RS = 1; // render scale: logical 960x600 drawn at device resolution
  function fit() {
    const s = Math.min(window.innerWidth / W, window.innerHeight / H); const dpr = window.devicePixelRatio || 1;
    RS = Math.max(1, Math.min(3, s * dpr));
    canvas.width = Math.round(W * RS); canvas.height = Math.round(H * RS);
    canvas.style.width = Math.floor(W * s) + 'px'; canvas.style.height = Math.floor(H * s) + 'px';
    ctx.setTransform(RS, 0, 0, RS, 0, 0); ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
  }
  window.addEventListener('resize', fit); fit();
  Audio.init(); Input.init(canvas);
  // build image list from the manifest embedded in ASSETS (generated by tools/list_assets.py)
  const images = ASSET_IMAGES, sounds = ASSET_SOUNDS;
  let progress = 0; const total = images.length + sounds.length;
  const drawLoading = () => { ctx.fillStyle = '#1a1626'; ctx.fillRect(0, 0, W, H); UI.text(ctx, 'sharpening crayons…', W / 2, H / 2 - 30, { size: 28, align: 'center' }); UI.bar(ctx, W / 2 - 200, H / 2 + 20, 400, 14, Assets.loaded / Math.max(1, Assets.total), '#ffd86b'); };
  drawLoading(); const iv = setInterval(drawLoading, 100);
  await Assets.loadAll(images, sounds); clearInterval(iv);
  // "click to start" so the AudioContext can resume
  let started = false; const startScreen = () => { ctx.fillStyle = '#1a1626'; ctx.fillRect(0, 0, W, H); UI.text(ctx, 'UNDRAWN', W / 2, H / 2 - 60, { size: 72, align: 'center', bold: true }); UI.text(ctx, 'press any key or click to open the sketchbook', W / 2, H / 2 + 30, { size: 22, align: 'center', color: '#cfc8e0' }); };
  startScreen();
  const go = () => { if (started) return; started = true; Audio.resume(); Scenes.push(new TitleScene()); Input.pressed = {}; Input.down = {}; loop(); };
  window.addEventListener('keydown', go, { once: true }); canvas.addEventListener('pointerdown', go, { once: true });
  let last = performance.now();
  function loop(now = performance.now()) {
    const dt = Math.min(0.05, (now - last) / 1000); last = now;
    ctx.setTransform(RS, 0, 0, RS, 0, 0);
    try { Scenes.update(dt); Scenes.draw(ctx); } catch (e) { console.error(e); }
    Input.endFrame(); requestAnimationFrame(loop);
  }
  // simple touch controls (mobile): tap zones
  let touchDir = null;
  canvas.addEventListener('touchstart', e => { const t = e.touches[0]; const r = canvas.getBoundingClientRect(); const x = (t.clientX - r.left) / r.width, y = (t.clientY - r.top) / r.height; if (x > 0.75) { Input.pressed.ok = true; Input.down.ok = true; setTimeout(() => Input.down.ok = false, 100); } else if (x < 0.25 && y < 0.2) { Input.pressed.menu = true; } else if (x < 0.25 && y > 0.8) { Input.pressed.cancel = true; } else { touchDir = Math.abs(x - 0.375) * 2 > Math.abs(y - 0.5) ? (x > 0.375 ? 'right' : 'left') : (y > 0.5 ? 'down' : 'up'); Input.down[touchDir] = true; } e.preventDefault(); }, { passive: false });
  canvas.addEventListener('touchend', () => { if (touchDir) Input.down[touchDir] = false; touchDir = null; });
})();
